#!/usr/bin/env python3
"""
analyze_candidate_coverage.py

Analyze candidate coverage JSON generated by 4DGS Viewer debug tools.

Typical use:
  python3 tools/analyze_candidate_coverage.py \
    --json /home/demo/work/json/step105_000151_v13_gpu_candidate_coverage.json

With output JSON:
  python3 tools/analyze_candidate_coverage.py \
    --json /home/demo/work/json/step105_000151_v13_gpu_candidate_coverage.json \
    --out-json /home/demo/work/json/step105_000151_v13_coverage_analysis.json

Compare multiple coverage JSON files:
  python3 tools/analyze_candidate_coverage.py \
    --json /home/demo/work/json/step105_000151_v13_gpu_candidate_coverage.json \
    --json /home/demo/work/json/step107_000151_v13_gpu_candidate_coverage.json
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    if path.stat().st_size == 0:
        raise ValueError(f"File is empty: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Top-level JSON value must be an object: {path}")
    return data


def get_path(obj: Any, paths: Iterable[str], default: Any = None) -> Any:
    for path in paths:
        cur = obj
        ok = True
        for part in path.split("."):
            if isinstance(cur, dict) and part in cur:
                cur = cur[part]
            elif isinstance(cur, list):
                try:
                    cur = cur[int(part)]
                except Exception:
                    ok = False
                    break
            else:
                ok = False
                break
        if ok:
            return cur
    return default


def as_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        if isinstance(value, bool):
            return int(value)
        return int(value)
    except Exception:
        return None


def as_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        if isinstance(value, bool):
            return float(value)
        return float(value)
    except Exception:
        return None


def compact_list(value: Any, max_items: int = 16) -> List[Any]:
    if not isinstance(value, list):
        return []
    if len(value) <= max_items:
        return value
    return value[:max_items]


def infer_step_from_path(path: Path) -> str:
    name = path.name
    suffix = "_gpu_candidate_coverage.json"
    if name.endswith(suffix):
        return name[: -len(suffix)]
    if name.endswith(".json"):
        return name[:-5]
    return name


def extract_coverage_object(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Coverage data may be top-level or nested under candidateCoverageSummary.
    Return the object that appears to contain coverage fields.
    """
    candidates = [
        data,
        get_path(data, ["candidateCoverageSummary"], {}),
        get_path(data, ["coverageSummary"], {}),
        get_path(data, ["limitedDrawSummary.candidateCoverageSummary"], {}),
        get_path(data, ["runtimeSummary.candidateCoverageSummary"], {}),
        get_path(data, ["summary.candidateCoverageSummary"], {}),
    ]

    best = data
    best_score = -1

    expected_keys = [
        "visibleHitCount",
        "visibleMissCount",
        "visibleCoverageRatio",
        "gpuCandidateCount",
        "candidateRangeCount",
        "cpuVisibleCount",
    ]

    for obj in candidates:
        if not isinstance(obj, dict):
            continue
        score = sum(1 for key in expected_keys if key in obj)
        if score > best_score:
            best_score = score
            best = obj

    return best


def safe_ratio(hit: Optional[int], total: Optional[int]) -> Optional[float]:
    if hit is None or total is None or total == 0:
        return None
    return hit / total


def summarize_missing_samples(samples: List[Any]) -> Dict[str, Any]:
    numeric: List[int] = []
    for item in samples:
        if isinstance(item, int):
            numeric.append(item)
        else:
            try:
                numeric.append(int(item))
            except Exception:
                pass

    if not numeric:
        return {
            "sampleCount": len(samples),
            "numericSampleCount": 0,
            "min": None,
            "max": None,
            "first": samples[:8],
        }

    return {
        "sampleCount": len(samples),
        "numericSampleCount": len(numeric),
        "min": min(numeric),
        "max": max(numeric),
        "first": numeric[:8],
    }


def classify_coverage(visible_ratio: Optional[float]) -> str:
    if visible_ratio is None:
        return "unknown"
    if visible_ratio == 0:
        return "none"
    if visible_ratio < 0.1:
        return "very_low"
    if visible_ratio < 0.5:
        return "low"
    if visible_ratio < 0.9:
        return "partial"
    if visible_ratio < 1.0:
        return "high"
    return "full"


def analyze_one(path: Path) -> Dict[str, Any]:
    data = load_json(path)
    cov = extract_coverage_object(data)

    visible_hit = as_int(get_path(cov, ["visibleHitCount"]))
    visible_miss = as_int(get_path(cov, ["visibleMissCount"]))
    cpu_visible = as_int(get_path(cov, ["cpuVisibleCount", "visibleCount"]))
    visible_ratio = as_float(get_path(cov, ["visibleCoverageRatio"]))

    if visible_ratio is None:
        total = cpu_visible
        if total is None and visible_hit is not None and visible_miss is not None:
            total = visible_hit + visible_miss
        visible_ratio = safe_ratio(visible_hit, total)

    packed_hit = as_int(get_path(cov, ["packedHitCount"]))
    packed_miss = as_int(get_path(cov, ["packedMissCount"]))
    packed_visible = as_int(get_path(cov, ["packedVisibleCount"]))
    packed_ratio = as_float(get_path(cov, ["packedCoverageRatio"]))

    if packed_ratio is None:
        total = packed_visible
        if total is None and packed_hit is not None and packed_miss is not None:
            total = packed_hit + packed_miss
        packed_ratio = safe_ratio(packed_hit, total)

    missing_visible = compact_list(
        get_path(cov, ["missingVisibleSrcIndices"], []),
        max_items=64,
    )
    missing_packed = compact_list(
        get_path(cov, ["missingPackedSrcIndices"], []),
        max_items=64,
    )

    candidate_count = as_int(
        get_path(cov, ["gpuCandidateCount", "candidateCount"])
    )
    range_start = as_int(
        get_path(cov, ["candidateRangeStart", "rangeStart"])
    )
    range_count = as_int(
        get_path(cov, ["candidateRangeCount", "rangeCount"])
    )

    source_mode = get_path(
        cov,
        ["sourceMode", "gpuCandidateSourceMode"],
        default=get_path(data, ["sourceMode", "gpuCandidateSourceMode"]),
    )

    display_source = get_path(
        data,
        [
            "displayCandidateSource",
            "runtimeSummary.displayCandidateSource",
            "limitedDrawSummary.displayCandidateSource",
        ],
    )

    used_for_display = get_path(
        data,
        [
            "gpuCandidateUsedForDisplay",
            "runtimeSummary.gpuCandidateUsedForDisplay",
            "limitedDrawSummary.gpuCandidateUsedForDisplay",
        ],
    )

    limited_used = get_path(
        data,
        [
            "limitedDrawUsedForCandidateSource",
            "runtimeSummary.limitedDrawUsedForCandidateSource",
            "limitedDrawSummary.limitedDrawUsedForCandidateSource",
        ],
    )

    result = {
        "path": str(path),
        "step": infer_step_from_path(path),
        "sourceMode": source_mode,
        "candidateRangeStart": range_start,
        "candidateRangeCount": range_count,
        "gpuCandidateCount": candidate_count,
        "cpuVisibleCount": cpu_visible,
        "visibleHitCount": visible_hit,
        "visibleMissCount": visible_miss,
        "visibleCoverageRatio": visible_ratio,
        "visibleCoveragePercent": None if visible_ratio is None else visible_ratio * 100.0,
        "visibleCoverageClass": classify_coverage(visible_ratio),
        "packedVisibleCount": packed_visible,
        "packedHitCount": packed_hit,
        "packedMissCount": packed_miss,
        "packedCoverageRatio": packed_ratio,
        "packedCoveragePercent": None if packed_ratio is None else packed_ratio * 100.0,
        "missingVisibleSampleSummary": summarize_missing_samples(missing_visible),
        "missingPackedSampleSummary": summarize_missing_samples(missing_packed),
        "displayCandidateSource": display_source,
        "gpuCandidateUsedForDisplay": used_for_display,
        "limitedDrawUsedForCandidateSource": limited_used,
    }

    return result


def print_one(result: Dict[str, Any]) -> None:
    print("Candidate coverage analysis")
    print(f"- file: {result['path']}")
    print(f"- step: {result['step']}")
    print(f"- sourceMode: {result['sourceMode']}")
    print(f"- candidateRangeStart: {result['candidateRangeStart']}")
    print(f"- candidateRangeCount: {result['candidateRangeCount']}")
    print(f"- gpuCandidateCount: {result['gpuCandidateCount']}")
    print(f"- cpuVisibleCount: {result['cpuVisibleCount']}")
    print(f"- visibleHitCount: {result['visibleHitCount']}")
    print(f"- visibleMissCount: {result['visibleMissCount']}")
    print(f"- visibleCoverageRatio: {format_ratio(result['visibleCoverageRatio'])}")
    print(f"- visibleCoverageClass: {result['visibleCoverageClass']}")
    print(f"- packedVisibleCount: {result['packedVisibleCount']}")
    print(f"- packedHitCount: {result['packedHitCount']}")
    print(f"- packedMissCount: {result['packedMissCount']}")
    print(f"- packedCoverageRatio: {format_ratio(result['packedCoverageRatio'])}")
    print(f"- displayCandidateSource: {result['displayCandidateSource']}")
    print(f"- gpuCandidateUsedForDisplay: {result['gpuCandidateUsedForDisplay']}")
    print(f"- limitedDrawUsedForCandidateSource: {result['limitedDrawUsedForCandidateSource']}")

    visible_sample = result["missingVisibleSampleSummary"]
    print(
        "- missingVisibleSample: "
        f"count={visible_sample['sampleCount']} "
        f"min={visible_sample['min']} "
        f"max={visible_sample['max']} "
        f"first={visible_sample['first']}"
    )


def format_ratio(value: Optional[float]) -> str:
    if value is None:
        return "-"
    if math.isnan(value):
        return "nan"
    return f"{value:.6f} ({value * 100.0:.3f}%)"


def print_comparison(results: List[Dict[str, Any]]) -> None:
    print("\nCoverage comparison table")
    headers = [
        "step",
        "source",
        "rangeStart",
        "rangeCount",
        "gpuCount",
        "visibleHit",
        "visibleMiss",
        "visibleRatio",
        "class",
    ]
    print(" | ".join(headers))
    print(" | ".join(["---"] * len(headers)))

    for r in results:
        row = [
            str(r["step"]),
            str(r["sourceMode"]),
            str(r["candidateRangeStart"]),
            str(r["candidateRangeCount"]),
            str(r["gpuCandidateCount"]),
            str(r["visibleHitCount"]),
            str(r["visibleMissCount"]),
            format_ratio(r["visibleCoverageRatio"]),
            str(r["visibleCoverageClass"]),
        ]
        print(" | ".join(row))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze candidate coverage JSON files."
    )
    parser.add_argument(
        "--json",
        action="append",
        required=True,
        help="Coverage JSON path. Can be specified multiple times.",
    )
    parser.add_argument(
        "--out-json",
        default=None,
        help="Optional output JSON path for analysis result.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    paths = [Path(p) for p in args.json]
    results = [analyze_one(path) for path in paths]

    for i, result in enumerate(results):
        if i > 0:
            print()
        print_one(result)

    if len(results) > 1:
        print_comparison(results)

    output = {
        "count": len(results),
        "results": results,
    }

    if args.out_json:
        out_path = Path(args.out_json)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(
            json.dumps(output, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
